version = 1

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "javascript"

[[transformers]]
name = "clang-format"